"""Tests for dotai.sync — agent bootstrap file generation."""

from pathlib import Path

from dotai.models import GlobalConfig, ProjectConfig, Role, Skill, SkillCategory
from dotai.sync import (
    DOTAI_MARKER_END,
    DOTAI_MARKER_START,
    _merge_with_markers,
    generate_claude_skill_md,
    generate_primer,
    sync_project,
)


class TestMergeWithMarkers:
    def test_first_sync_appends(self):
        result = _merge_with_markers("# My Project\n\nCustom stuff.", "Generated content")
        assert "# My Project" in result
        assert "Custom stuff." in result
        assert DOTAI_MARKER_START in result
        assert "Generated content" in result
        assert DOTAI_MARKER_END in result

    def test_resync_replaces(self):
        existing = f"Header\n\n{DOTAI_MARKER_START}\nOld content\n{DOTAI_MARKER_END}\n"
        result = _merge_with_markers(existing, "New content")
        assert "Old content" not in result
        assert "New content" in result
        assert "Header" in result

    def test_preserves_after_marker(self):
        existing = f"Before\n\n{DOTAI_MARKER_START}\nOld\n{DOTAI_MARKER_END}\nAfter"
        result = _merge_with_markers(existing, "New")
        assert "Before" in result
        assert "New" in result
        assert "After" in result


class TestGeneratePrimer:
    def test_contains_structure(self, ai_dir, config):
        primer = generate_primer(config)
        assert "# AI Knowledge Base" in primer
        assert "~/.ai/" in primer

    def test_includes_roles(self, ai_dir, config, sample_role_file):
        primer = generate_primer(config)
        assert "Test Reviewer" in primer
        assert "## Available Roles" in primer

    def test_includes_skills(self, ai_dir, config, sample_skill_file):
        primer = generate_primer(config)
        assert "Test Skill" in primer
        assert "## Available Skills" in primer

    def test_includes_rules(self, ai_dir, config, sample_rule_file):
        primer = generate_primer(config)
        assert "no-console-log" in primer
        assert "## Active Rules" in primer

    def test_scoped_to_project(self, ai_dir, tmp_path):
        """Project-scoped roles/skills from other projects should not appear."""
        (ai_dir / "roles" / "global.md").write_text(
            "---\nname: Global\ndescription: G\n---\nGlobal.\n"
        )
        proj = tmp_path / "proj"
        proj.mkdir()
        proj_roles = proj / ".ai" / "roles"
        proj_roles.mkdir(parents=True)
        (proj_roles / "local.md").write_text(
            "---\nname: Local\ndescription: L\n---\nLocal.\n"
        )

        config = GlobalConfig(
            global_ai_dir=ai_dir,
            projects=[ProjectConfig(name="proj", path=proj)],
        )
        primer = generate_primer(config, project_name="proj")
        assert "Global" in primer
        assert "Local" in primer


class TestGenerateClaudeSkillMd:
    def test_basic_output(self):
        skill = Skill(
            id="test-skill",
            name="Test Skill",
            description="Run tests.",
            trigger="/run_test",
            category=SkillCategory.VERIFICATION,
            allowed_tools=["Read", "Bash"],
            steps=["Find runner", "Run tests"],
        )
        roles = [
            Role(id="qa", name="QA", description="Tester", persona="You test."),
        ]
        md = generate_claude_skill_md(skill, roles)
        assert "name: run_test" in md
        assert "Auto-generated by dotai" in md
        assert "$ARGUMENTS" in md
        assert "Role: qa" in md
        assert "# Skill: Test Skill" in md

    def test_argument_hint(self):
        skill = Skill(id="s", name="S", description="D", trigger="/run_s", steps=["Go"])
        md = generate_claude_skill_md(skill, [])
        assert 'argument-hint: "[as <role>]"' in md


class TestSyncProject:
    def test_creates_all_files(self, ai_dir, project_dir, config):
        written = sync_project(project_dir, config)
        filenames = [Path(f).name for f in written]
        assert "CLAUDE.md" in filenames
        assert ".cursorrules" in filenames
        assert "GEMINI.md" in filenames
        assert "AGENTS.md" in filenames

    def test_filter_agents(self, ai_dir, project_dir, config):
        written = sync_project(project_dir, config, agents=["claude"])
        filenames = [Path(f).name for f in written]
        assert "CLAUDE.md" in filenames
        assert ".cursorrules" not in filenames

    def test_claude_skills_created(self, ai_dir, project_dir, config, sample_skill_file):
        written = sync_project(project_dir, config, agents=["claude"])
        skill_files = [f for f in written if "SKILL.md" in f]
        assert len(skill_files) == 1
        assert "run_test" in skill_files[0]

    def test_resync_preserves_custom_content(self, ai_dir, project_dir, config):
        # First sync
        sync_project(project_dir, config, agents=["claude"])

        # Add custom content to CLAUDE.md
        claude_path = project_dir / "CLAUDE.md"
        content = claude_path.read_text()
        claude_path.write_text("# My Custom Header\n\n" + content)

        # Resync
        sync_project(project_dir, config, agents=["claude"])
        result = claude_path.read_text()
        assert "# My Custom Header" in result
        assert DOTAI_MARKER_START in result

    def test_stale_skills_cleaned(self, ai_dir, project_dir, config, sample_skill_file):
        # First sync with a skill
        sync_project(project_dir, config, agents=["claude"])
        assert (project_dir / ".claude" / "skills" / "run_test" / "SKILL.md").exists()

        # Remove the skill source and resync
        sample_skill_file.unlink()
        sync_project(project_dir, config, agents=["claude"])
        assert not (project_dir / ".claude" / "skills" / "run_test").exists()
